---
title: "Group 1: Monopoly"
output: word_document
date: "2025-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section One
```{r}
# Word docx in repository
```


## Section Two
```{r}
dice_1 <- function() {
  sample(1:6, 1)
}

dice_2 <- function() {
  sample(1:6, 1)
}

property_sum_10games <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

for (game in 1:10) {
  game_board <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

  players <- list(
    player1 <- 0,
    player2 <- 0,
    player3 <- 0,
    player4 <- 0
  )

  for (i in 1:50) {
    for (j in 1:4) {
      dice_total <- dice_1() + dice_2()
      players[[j]] <- (players[[j]] + dice_total) %% 41
      game_board[players[[j]]] <- game_board[players[[j]]] + 1
    }
  }

  properties <- game_board[c(2, 4, 6, 7, 9, 10, 12, 13, 14, 15, 16, 17, 19, 20, 22, 24, 25, 26, 27, 28, 29, 30, 32, 33, 35, 36, 38, 40)]
  
  property_sum_10games <- property_sum_10games + properties
}  

names(property_sum_10games) <- c("Mediterranean Avenue", "Baltic Avenue", "Reading Railroad", "Oriental Avenue", "Vermont Avenue", "Connecticut Avenue", "St. Charles Place", "Electric Company", "States Avenue", "Virginia Avenue", "Pennsylvania Railroad", "St. James Place", "Tennessee Avenue", "New York Avenue", "Kentucky Avenue", "Indiana Avenue", "Illinois Avenue", "B&O Railroad", "Atlantic Avenue", "Ventnor Avenue", "Water Works", "Marvin Gardens", "Pacific Avenue", "North Carolina Avenue", "Pennsylvania Avenue", "Short Line", "Park Place", "Boardwalk")

library(ggplot2)

prop_freq1 <- data.frame(
  property = factor(names(property_sum_10games), levels = names(property_sum_10games)),
  frequency = property_sum_10games
)

ggplot(prop_freq1, aes(x = property, y = frequency)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Index", y = "Frequency", title = "Bar Plot of Property Frequencies") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Section Three
```{r}
property_sum_10games_jail <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

for (game in 1:10) {
  game_board <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

  players <- list( # Store players as a list of data frames with their information
    player1 <- data.frame(
      location = 0, # Location on the board (integer)
      double_rolls = 0, # Number of times doubles have been rolled consecutively (integer)
      jail = FALSE, # Is the player in jail? (boolean)
      jail_rolls = 0), # Number of times a player has rolled while in jail (integer)
    player2 <- data.frame(
      location = 0,
      double_rolls = 0,
      jail = FALSE,
      jail_rolls = 0),
    player3 <- data.frame(
      location = 0,
      double_rolls = 0,
      jail = FALSE,
      jail_rolls = 0),
    player4 <- data.frame(
      location = 0,
      double_rolls = 0,
      jail = FALSE,
      jail_rolls = 0)
  )

  for (i in 1:50) { # Each player has 50 turns
    for (j in 1:4) { # Players take turns in order
      if (players[[j]]$jail == TRUE) { # If the player is in jail...
        d1 = dice_1()
        d2 = dice_2()
        jail_rolls <- jail_rolls + 1
        
        if (d1 == d2 || players[[j]]$jail_rolls == 3) { # If the player rolls doubles or has been in jail for 3 turns, then they get out
          jail = FALSE
          players[[j]]$jail_rolls <- 0
          dice_total <- dice_1() + dice_2()
          players[[j]]$location <- (players[[j]]$location + dice_total) %% 41
          game_board[players[[j]]$location] <- game_board[players[[j]]$location] + 1
        }
        
      } else { # If the player is not in jail...
        d1 = dice_1()
        d2 = dice_2()
        dice_total <- dice_1() + dice_2()
        players[[j]]$location <- (players[[j]]$location + dice_total) %% 41
        game_board[players[[j]]$location] <- game_board[players[[j]]$location] + 1
        
        if (players[[j]]$location == 31) { # Player landed on "Go to jail"
          players[[j]]$location <- 11
          jail = TRUE
        } else if (d1 == d2) { # Player rolled doubles on their first roll
          players[[j]]$double_rolls = players[[j]]$double_rolls + 1
        }
        
        while (players[[j]]$double_rolls > 0 & players[[j]]$double_rolls < 3) { # Player rolls again if they got doubles
          d1 = dice_1()
          d2 = dice_2()
          dice_total <- dice_1() + dice_2()
          players[[j]]$location <- (players[[j]]$location + dice_total) %% 41
          game_board[players[[j]]$location] <- game_board[players[[j]]$location] + 1
          
          if (d1 == d2) { # Increment the player's number of consecutive doubles rolls
            players[[j]]$double_rolls = players[[j]]$double_rolls + 1
          }
        }
        
        if (players[[j]]$double_rolls == 3) { # If player rolls double 3 times in a row, then they go to jail
          players[[j]]$location <- 11
          jail = TRUE
        }
      }
    }  
  }    

  properties <- game_board[c(2, 4, 6, 7, 9, 10, 12, 13, 14, 15, 16, 17, 19, 20, 22, 24, 25, 26, 27, 28, 29, 30, 32, 33, 35, 36, 38, 40)]
  
  property_sum_10games_jail <- property_sum_10games_jail + properties
}  

names(property_sum_10games_jail) <- c("Mediterranean Avenue", "Baltic Avenue", "Reading Railroad", "Oriental Avenue", "Vermont Avenue", "Connecticut Avenue", "St. Charles Place", "Electric Company", "States Avenue", "Virginia Avenue", "Pennsylvania Railroad", "St. James Place", "Tennessee Avenue", "New York Avenue", "Kentucky Avenue", "Indiana Avenue", "Illinois Avenue", "B&O Railroad", "Atlantic Avenue", "Ventnor Avenue", "Water Works", "Marvin Gardens", "Pacific Avenue", "North Carolina Avenue", "Pennsylvania Avenue", "Short Line", "Park Place", "Boardwalk")

library(ggplot2)

prop_freq2 <- data.frame(
  property = factor(names(property_sum_10games_jail), levels = names(property_sum_10games_jail)),
  frequency = property_sum_10games_jail
)

ggplot(prop_freq2, aes(x = property, y = frequency)) +
  geom_bar(stat = "identity", fill = "pink") +
  labs(x = "Index", y = "Frequency", title = "Bar Plot of Property Frequencies\nWith Jail and Doubles Conditions") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


## Section Four
```{r}

```

## Section Five
```{r}


```



